# START BENCHMARK
if [[ "${ZSH_BENCHMARK:l}" == "yes" ]]; then
    zmodload zsh/datetime 2>/dev/null
    zmodload zsh/zprof 2>/dev/null
    typeset -g ZSH_BENCHMARK_START=$EPOCHREALTIME
fi

# ZSH Cache dir
: "${ZSH_CACHE:=${XDG_CACHE_HOME:-$HOME/.cache}/zsh}"
mkdir -p "$ZSH_CACHE"

# Enable colors and change prompt:
autoload -U colors && colors
#PS1="%B%{$fg[white]%}[%{$fg[yellow]%}%n%{$fg[green]%}@%{$fg[blue]%}%M %{$fg[magenta]%}%~%{$fg[white]%}]%{$reset_color%}$%b "
PS1="%B%{$fg[white]%}[%{$fg[green]%}%n %{$reset_color%}in %{$fg[magenta]%}%~%{$fg[white]%}]%{$reset_color%}$%b "

# History in cache directory:
HISTFILE="$ZSH_CACHE/history"
HISTSIZE=10000
SAVEHIST="$HISTSIZE"
HISTORY_IGNORE='(ls|cd|pwd|exit|sudo reboot|history|cd -|cd ..|rm *|rf *)'
setopt share_history                # Share history immediately across running tabs/panes
setopt extended_glob                # Enable advanced pattern matching (needed for IGNORE)
setopt inc_append_history
setopt inc_append_history_time
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_space
setopt hist_reduce_blanks

# If only Dir path, cd there
setopt autocd

# Basic auto/tab completion:
ZCOMPCACHE="$ZSH_CACHE/zcompcache"
ZSH_COMPLETION_DUMP="$ZCOMPCACHE/.zcompdump"

mkdir -p "$ZCOMPCACHE"

autoload -U compinit
zmodload zsh/complist
_comp_options+=(globdots)           # Include hidden files.
                                    # Completion behavior
zstyle ':completion:*' menu select
zstyle ':completion:*' increment yes
zstyle ':completion:*' use-cache true
zstyle ':completion:*' cache-path $ZCOMPCACHE
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' list-dirs-first yes
zstyle ':completion:*' completer _complete _match _approximate
zstyle ':completion:*:approximate:*' max-errors 2 numeric
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*:*:*:*:commands' ignored-patterns '/mnt/c/*' '/mnt/d/*' '/mnt/e/*'

# Completion dump init every 24H
# Also disable global compinit in /etc/zsh/zshrc
if [[ ! -f "$ZSH_COMPLETION_DUMP" || -n "$ZSH_COMPLETION_DUMP"(#qN.mh+24) ]]; then
    compinit -i -d "$ZSH_COMPLETION_DUMP"
    touch "$ZSH_COMPLETION_DUMP"
else
    compinit -C -d "$ZSH_COMPLETION_DUMP"
fi
# Compile dump for speed
if [[ ! -f "$ZSH_COMPLETION_DUMP.zwc" || "$ZSH_COMPLETION_DUMP" -nt "$ZSH_COMPLETION_DUMP.zwc" ]]; then
    zcompile "$ZSH_COMPLETION_DUMP" &!
fi

unset ZCOMPCACHE
unset ZSH_COMPLETION_DUMP

# Aliases
if [ -f $HOME/.aliasrc ]; then
    source $HOME/.aliasrc
fi

# Benchmarking

alias tz='repeat 20 { { /usr/bin/time -p zsh -i -c exit >/dev/null; } 2>&1; } | awk '\''/^real / {x=$2; sum+=x; n++; if(n==1||x<min)min=x; if(n==1||x>max)max=x} END {printf "avg: %.4f s | min: %.4f | max: %.4f\n", sum/n, min, max}'\'''
zbench() {
  env ZSH_BENCHMARK=yes zsh -i -c exit
}
alias zb='zbench'

# Plugins
source "$HOME/.local/share/zsh/zsh-defer/zsh-defer.plugin.zsh" # Defer non-essential plugins.
zsh-defer source "$HOME/.local/share/zsh/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh"
# zsh-defer source "$HOME/.local/share/zsh/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh"
zsh-defer eval "$(zsh-patina activate)"
zsh-defer source "$HOME/.local/share/zsh/zsh-history-substring-search/zsh-history-substring-search.plugin.zsh"
# Transient prompt
TRANSIENT_PROMPT_PROMPT="$PS1"
TRANSIENT_PROMPT_RPROMPT="$RPROMPT"
TRANSIENT_PROMPT_TRANSIENT_PROMPT='%F{242}❯%f '
TRANSIENT_PROMPT_TRANSIENT_RPROMPT=''
zsh-defer source "$HOME/.local/share/zsh/zsh-transient-prompt/transient-prompt.plugin.zsh"

# Keyboard
bindkey '^[[3~' delete-char  # Delete
bindkey '^[[Z' reverse-menu-complete  # Shift+Tab
bindkey '^[[1;5D' backward-word  # Control-Left
bindkey '^[[1;5C' forward-word  # Control-Right

## History substring
bindkey '^[[1;2A' history-substring-search-up # or '\eOA'
bindkey '^[[1;2B' history-substring-search-down # or '\eOB'

#-- From Bashrc
# Lazy-load lesspipe for better non-text file support; see lesspipe(1)
less() {
  unset -f less
  [ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"
  command less "$@"
}

# Load Angular CLI autocompletion.
#source <(ng completion script)

# END BENCHMARKING
if [[ "${ZSH_BENCHMARK:l}" == "yes" && -n "${ZSH_BENCHMARK_START:-}" ]]; then
  typeset -F 3 total_ms
  total_ms=$(( (EPOCHREALTIME - ZSH_BENCHMARK_START) * 1000 ))

  print
  print -P "%B%F{yellow}ZSH STARTUP BENCHMARK%f%b"
  print -P "Total startup time: %F{cyan}${total_ms} ms%f"
  print
  if zmodload -e zsh/zprof; then
    printf '  %-34s %10s %8s %8s\n' "FUNCTION" "TIME(ms)" "CALLS" "LOAD"

    zprof | awk '
      BEGIN { shown = 0 }
      /^[[:space:]]*[0-9]+\)/ {
        name = $NF
        calls = $2
        time  = $3
        pct   = $5

        if (seen[name]++) next
        if (shown++ >= 10) exit

        if (length(name) > 32) {
          name = substr(name, 1, 29) "..."
        }

        printf "  %-32s %10.2f %8s %7.2f%%\n", name, time, calls, pct
      }
    '
  fi

  unset ZSH_BENCHMARK_START total_ms
fi
